Post.delete_all
City.delete_all

user1 = User.create(email: 'user1@user.com', password: '123456', full_name: 'Clark Kent', current_city: 'Atlanta', image: 'https://vignette2.wikia.nocookie.net/superman/images/7/7e/ClarkKent_Reporter.jpg/revision/latest?cb=20130617171011' )
user2 = User.create(email: 'user2@user.com', password: '123456', full_name: 'Bruce Banner', current_city: 'Atlanta', image: 'https://pbs.twimg.com/profile_images/448409779153547264/pARLjjG2.jpeg' )

atlanta = City.create(name: 'Atlanta', state: 'Georgia', image: 'http://i.huffpost.com/gen/1716876/images/o-ATLANTA-TRAFFIC-facebook.jpg')
sanfrancisco = City.create(name: 'San Francisco', state: 'California', image: 'http://www.mckinsey.com/~/media/McKinsey/Locations/North%20America/West%20Coast/San%20Francisco/WCO_SanFrancisco_hero_GettyImages-476881195_1536x768_crop-left_2.ashx?mw=1536&car=546:205&cpx=Left&cpy=Center')
lasvegas = City.create(name: 'Las Vegas', state: 'Nevada', image: 'http://i.huffpost.com/gen/2702814/images/o-LAS-VEGAS-facebook.jpg')
london = City.create(name: 'London', state: 'England', image: 'http://www.gdcc.com/wp-content/uploads/2013/12/2-London.jpg')

Post.create(title: "Tour The Georgia Aquarium", post: "If you're in Atlanta you should go to the Georgia Aquarium. It's amazing!! And if you go splurge for the behind the scenes tour. You get to see the aquarium from behind the scenes, and you won't ever forget the experience!", city_id: atlanta.id, user_id: user1.id, img: "https://www.georgiaaquarium.org/images/default-source/default-album/bts-411x411-logoa4fec313cabb6b4c8326ff00008b2be6.png?sfvrsn=1")
Post.create(title: "Atlanta Southern Food Tour", post: "Your Atlanta food tour takes you off-the-beaten path to Atlanta's historic downtown neighborhoods to try 15 mouth-watering tastings from 7 restaurants and food shops. The 3.5 hour small group tour will introduce you to the history and diversity of Southern food as you try soul food, barbecue, Lowcountry cuisine, Creole-style candies, and today’s newest Southern specialties.", city_id: atlanta.id, user_id: user1.id, img:"http://www.bravotv.com/sites/nbcubravotv/files/styles/blog-post--mobile/public/field_blog_image/2016/05/the-feast-southern-foods-up-north-promote.jpg?itok=EbxPL6N2&timestamp=1464191684")
Post.create(title: "Try Hops Chicken!", post: "This is a great spot to try if you haven't already. They have a simple menu of chicken & side items, a decent beer list as well. I had the Nashville-Hot Chicken Sandwich with a side of Mac & cheese. The sandwich came with sweet pickles only but they offered mayo, hot sauce, ketchup, & other condiment options. The chicken was perfectly crispy but still juicy. I loved how they scoop the Mac & cheese so there's a crispy layer underneath. Best chicken I've had outside of Nashville!", city_id: atlanta.id, user_id: user1.id, img:"https://lh3.googleusercontent.com/r2-SimbKshI50daxxJ5RjKXevZIAvh6gpi3G20TBsI5M_sv94M2knQmP_FrZSPU=s1024")
Post.create(title: "Check Out The Fox Theater!", post: 'Recently restored to its original gilded look of the 1920s, the Fox Theatre features "Mighty Mo", a classic Moller organ with over 3,600 pipes. The lavish theatre currently hosts Broadway musicals, comedy shows and dance companies throughout the year.', city_id: atlanta.id, user_id: user2.id, img:"http://sponsorship.michiganradio.org/wp-content/uploads/2015/04/Fox-Theatre-1.jpg")

Post.create(title: "Tour Buckingham Palace", post: "Buckingham Palace, the London home of Queen Elizabeth II, is open for tour (except for the queen's private quarters, of course) in the summers. On the tour, you'll have access to the 19 State Rooms where the queen and members of the royal family host guests for state, ceremonial, and official affairs. It's so beautiful!! I recommend the audio tour.", city_id: london.id, user_id: user2.id, img:"http://static.travel.usnews.com/dims4/USNEWS/a21d1e6/2147483647/resize/637x426%3E/quality/85/?url=/images/destinations/82/80471741.jpg")
Post.create(title: "The National Gallery! So Amazing!!", post: "Sitting in Trafalgar Square, London's National Gallery features a labyrinth interior so large that it requires a color-coded map to navigate. The museum features paintings in the Western European tradition from the 13th to 19th centuries, including Italian Renaissance masterpieces and French Impressionist works. Among its 2,300 in-house pieces, visitors will find famed paintings such as Botticelli's Venus and Mars and Van Gogh's Sunflowers.", city_id: london.id, user_id: user2.id, img:"http://static.travel.usnews.com/dims4/USNEWS/f3fc9e9/2147483647/resize/637x426%3E/quality/85/?url=/images/destinations/82/6240788758_da1e78a77e_b.jpg")
Post.create(title: "Visit Tower Bridge", post: "Along with Parliament and Big Ben, Tower Bridge is London's next must-see architectural marvel, not to mention the most famous bridge that crosses the Thames. Built a mere 120 years ago, the bridge not only stands out for its stunning detail but moveable roadways that lift up when large ships need to pass through. The views from the bridge are an added bonus. From the elevated sidewalks visitors get a prime view of the city.", city_id: london.id, user_id: user1.id, img:"http://static.travel.usnews.com/dims4/USNEWS/8462b57/2147483647/resize/637x426%3E/quality/85/?url=/images/destinations/82/494764110.jpg")
Post.create(title: "The London Eye Ferris Wheel", post: "The London Eye (the giant Ferris wheel found in many London panoramas) located on the River Thames is meant to deliver great views – not a thrilling ride. It circles around slowly, offering an unbeatable birds-eye perspective of London's South Bank. However, those with a fear of heights should beware: When you're more than 400 feet high, the 360-degree views can be a bit disconcerting.", city_id: london.id, user_id: user1.id, img:"http://www.telegraph.co.uk/content/dam/Travel/leadAssets/31/82/London_Eye_view_3182851a-large.jpg")

Post.create(title: "Why Else Would You Go To Vegas", post: "If you're going to vegas it's going to be because we what to see/stay at the strip. We spent a week in Vegas and between all the activities, shows, shopping and different hotels to see you won't be bored. It was ridiculously hot so make sure to always have some water on hand. The souvenirs stores sell 2 bottles for $1 you can't beat that! The Strip is an amazing place always.", city_id: lasvegas.id, user_id: user2.id, img:"http://www.destination360.com/north-america/us/nevada/las-vegas/images/las-vegas-night.jpg")
Post.create(title: "GUNS!", post: "We wanted something different to do and MGV was a great choice. My 20 year old son and 18 year old daughter had a blast (literally). The prices are reasonable and the instructors are very safe. You can choose from a wide variety of guns to shoot.", city_id: lasvegas.id, user_id: user2.id, img:"http://www.lasvegasstrip.net/images/tours/gunstore/las-vegas-gun-store-machine-gun.jpg")
Post.create(title: "Hoover Dam and Grand Canyon", post: "Experience one of the seven natural wonders of the world from the land, air and water on this guided, full-day tour from Las Vegas to the Grand Canyon. Travel through a Joshua tree forest with a photo stop at Hoover Dam en route to the Grand Canyon’s West Rim for three hours of sightseeing. Upgrade to add a thrilling walk on the glass-bottomed Grand Canyon Skywalk and/or a helicopter flight into the canyon coupled with a pontoon boat ride on the Colorado River. Lunch and hotel pickup and drop-off are included.", city_id: lasvegas.id, user_id: user1.id, img:"https://www.canyontours.com/wp-content/uploads/2014/03/HD1.png")

Post.create(title: "Alcatraz Tour - So Cool!", post: "Get your tickets as soon as they release your dates. We were there in early June and a sign on the pier said the next available tour was July 12th. Luckily we had tickets already. It was a nice boat ride to the Island. Beware there is a good hill to climb to start the tour but I have faith that if I can do it, so can you! The tour is via headset but quite good. YOu will not be disappointed. Our entire family has marked this as a favorite for sure!", city_id: sanfrancisco.id, user_id: user2.id, img:"http://www.history.com/images/media/video/history_mysteryquest_alcatraz_sf_1147376/alcatraz-mystery-thumb_still_624x352.jpg")
Post.create(title: "Golden Gate Bridge - Amazing View", post: "Great views of the bay and Alcatraz minutes outside out San Francisco. Can be colder and more windy than you expect so recommend you bring a light jacket. You can walk, jog or ride a bicycle across. Parking can fill up and seemed to be more congested across the bridge from SF.", city_id: sanfrancisco.id, user_id: user2.id, img:"http://assets.inhabitat.com/wp-content/blogs.dir/1/files/2017/01/golden-gate-bridge-2.jpg")
Post.create(title: "Wow - San-Francisco Bay Is Amazing!", post: "Just look at the picture. I didn't want to leave.", city_id: sanfrancisco.id, user_id: user1.id, img:"http://www.visitcalifornia.com/sites/default/files/styles/welcome_image/public/VCW_TI_5_BayLoop_Hero_Manley_1280x642_sized_0.jpg")

puts "seeds complete"